apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeip
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubeip
  template:
      metadata:
        labels:
          app: kubeip
      spec:
        priorityClassName: system-cluster-critical
        containers:
        - name: "kubeip"
          image: hub.docker.com/r/doitintl/kubeip:latest
          imagePullPolicy: Always
          volumeMounts:
          - name: google-cloud-key
            mountPath: /var/secrets/google
          env:
          - name: "KUBEIP_LABELKEY"
            valueFrom:
              configMapKeyRef:
                key: "KUBEIP_LABELKEY"
                name: "kubeip-config"
          - name: "KUBEIP_LABELVALUE"
            valueFrom:
              configMapKeyRef:
                key: "KUBEIP_LABELVALUE"
                name: "kubeip-config"
          - name: "KUBEIP_NODEPOOL"
            valueFrom:
              configMapKeyRef:
                key: "KUBEIP_NODEPOOL"
                name: "kubeip-config"

          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /var/secrets/google/key.json
        restartPolicy: Always
        volumes:
          - name: google-cloud-key
            secret:
              secretName: kubeip-key

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kubeip-rbac
subjects:
  - kind: ServiceAccount
    # Reference to upper's `metadata.name`
    name: default
    # Reference to upper's `metadata.namespace`
    namespace: default
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
