apiVersion: v1
data:
  KUBEIP_LABELKEY: "kubeip"
  KUBEIP_LABELVALUE: "reserved"
  KUBEIP_NODEPOOL: "default-pool"
  KUBEIP_FORCEASSIGNMENT: "true"
  KUBEIP_ADDITIONALNODEPOOLS: ""
  KUBEIP_TICKER: "5"
  KUBEIP_ALLNODEPOOLS: "false"
kind: ConfigMap
metadata:
  labels:
    app: kubeip
  name: kubeip-config
  namespace: kube-system
